# Server Information
server:
  ip: play.ourmcworld.ml # Server IP
  port: 39703 # Server port
  version: # Server version (keep empty to use supported version)

# Victims username
players:

# Other Settings
connect-interval: 3000 # Connection interval to prevent "Connection throttled!"
output-file: records.yml # Output file

# Version
version: 1.3 # Config version (Don't modify)
