# Server Information
server:
  ip: 'ZUCHINIsmp.aternos.me' # Server IP
  port: 27156 # Server port
  version: # Server version (keep empty to use supported version)

# Victims username
players:
  - 'luizn2010'
  - 'Wackin'
  - 'beebow'
  - 'GhexterCortes'
  - 'AlphaMegaKing'

# Other Settings
connect-interval: 3000 # Connection interval to prevent "Connection throttled!"
output-file: coordinates.yml # Output file

# Version
version: 0.1 # Config version (Don't modify)