# Server Information
server:
  ip: play.ourmcworld.ml # Server IP
  port: 25565 # Server port
  version: # Server version (keep empty to use supported version)

# Victims username
players: [Grigora1, Grigora2, Grigora3]

# Other Settings
connect-interval: 5000 # Connection interval to prevent "Connection throttled!"
output-file: records.yml # Output file

# Version
version: 2.0.0 # Config version (Don't modify)
